apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-fywi
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0071-tenant/tkrw-pr712-0075-0071-app/devfile-sample-fywi@sha256:9a13f05249709a00a6d1ab947d85de8f8e0935e6d4afa5dddd2a42f403d0c165
        name: my-nodejs
        resources: {}
status: {}
